name: CI - 빌드 및 린트 테스트

on: [pull_request]

jobs:
  build-and-lint:
    if: |
      github.actor == 'hyun907' || 
      github.actor == 'ssilver01'

    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 노드 설치
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: pnpm 설치
        uses: pnpm/action-setup@v4

      - name: 의존성 캐시
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 의존성 설치
        run: pnpm install

      - name: 타입 체크
        run: pnpm check-types

      - name: 린트 체크
        run: pnpm lint

      - name: 코드 포맷 체크
        run: pnpm prettier

      - name: 빌드 실행
        run: pnpm build
