name: PR Preview

on:
  pull_request:
    branches: [main, develop]

jobs:
  vercel-preview:
    if: |
      github.actor == 'hyun907' || 
      github.actor == 'ssilver01'

    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: pnpm ì„¤ì¹˜
        uses: pnpm/action-setup@v4

      - name: ë…¸ë“œ ì„¤ì¹˜
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Vercel CLI ì„¤ì¹˜
        run: npm install --global vercel@latest

      - name: Vercel í™˜ê²½ë³€ìˆ˜ ê°€ì ¸ì˜¤ê¸°
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./apps/web

      - name: í”„ë¡œì íŠ¸ ë¹Œë“œ
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./apps/web

      - name: Vercelì— ë°°í¬
        id: deploy
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > vercel-output.txt
          echo "preview_url=$(cat vercel-output.txt)" >> $GITHUB_OUTPUT
        working-directory: ./apps/web

      - name: PRì— Preview URL ëŒ“ê¸€ ì¶”ê°€
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ğŸ‰ êµ¬í˜„í•œ ê¸°ëŠ¥ Preview: ${{ steps.deploy.outputs.preview_url }}
